language: java
jdk:
  - oraclejdk8
before_install:
  - pip install --user codecov
  - cp sample/copper.properties target/
  - cp -r sample/stories target/
after_success:
  - mvn clean test jacoco:report
  - codecov