language: java
jdk:
  - oraclejdk8
before_install:
  - pip install --user codecov
  - cp sample/copper.properties .
  - cp -r sample/stories .
after_success:
  - mvn clean install
  - mvn test jacoco:report
  - codecov