language: java
jdk:
  - oraclejdk8
before_install:
  - pip install --user codecov
after_success:
  - mvn clean install
  - cp sample/copper.properties target/
  - cp -r sample/stories target/
  - mvn test jacoco:report
  - codecov