language: java
jdk:
  - oraclejdk8
script:
- mvn clean install --settings src/test/mvnsettings.xml
cache:
  directories:
    - '$HOME/.m2/repository'
before_install:
  - pip install --user codecov
  - cp sample/copper.properties .
  - cp -r sample/stories .
after_success:
  - mvn clean install
  - mvn test jacoco:report
  - codecov